sudo: false  # Use container-based infrastructure
language: python
python:
  - "2.7"
  - "3.5"
before_install:
  # Commands below copied from: http://conda.pydata.org/docs/travis.html
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  # reset the shell's lookup table for program name to path mappings
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
install:
  - >
      conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
      nose pylint
  - source activate test-environment
  - pip install pypandoc
  - pip install -r requirements.txt
  - pip install .
  - pip install coveralls
script:
  # run tests
  - nosetests test --with-coverage --cover-package=mhcnames  && ./lint.sh
after_success:
  coveralls
deploy:
  provider: pypi
  distributions: sdist
  user: hammerlab
  password: # See http://docs.travis-ci.com/user/encryption-keys/
    secure: "BwIahNcb4koDiC8xP3ZsesqrYPzcNM2KuYA4CCtRNGntmY4Sjgb6Kcd3FXFwUtIbvFCqMHkRKHtx3uC8ZDNHPRnZ4VW1M3pyWyj9UYzX447imgsgQNDJJnbjotJ2c2jkfSQ6MyfbFdY5WALRUZTX6GcaZV4PzsHFBI/Ty8COtrnowUryLUs1amAIIBrOCSS/0TYd9Rh9Or8s3y/OqEDNHQDbZQ+ywQNt0wCwQWYtRIILgtR9grVM6k647S8gcTXudX8sJ7uzR8ebooXDdAF2ZxXJGX6kPongReghc9xliYuVzjhRvTJ0o4bDLhOrtpUGtbheTZdGv+OQohmiKlpr0mr833xGYq607BNUf1dUkuyyQt3D+lEEWyWQxScmq8feMvfNj1LKZ/eFR+6Svessh8S1NPfrfn8NMTC/d2u6oagqYb0zZXKYCs83zKjRX6uc4/PXVDLJvgQvpyiCD3SW48RVoLZbiyQ1TO36ph5Xxj9egPnRtIGu1obL3T1UyR31ZykU1NZ/kJHGVRFzU8sKJLAmnzYbe7NMS3AQoocM7af9UTDWBuHIqP5+NqljLkwlIITITEje9cYMgEiZaDCqzkFeKAJLchWPmoT6Bu9ECTB2mfAVVhy8/8XbFYu4CsnEXre28/iofVjO8u5wOkUCYNx2qqkuDBWtv7yUSstXItc="
  on:
    branch: master
